#!/bin/bash
# 2026-05-19
# Generated by Gemini
# Objective: convert all the images stored in the folder to the same width
# Usage: ./resize_images.sh <target_width> [target_directory]
# Example: ./resize_images.sh 800 ./my_photos


# Check if the user provided a width
if [ -z "$1" ]; then
    echo "Usage: $0 <target_width> [target_directory]"
    echo "Example: $0 800 ./my_photos"
    exit 1
fi

TARGET_WIDTH=$1
TARGET_DIR=${2:-.} # Defaults to the current directory if not provided
OUT_DIR="${TARGET_DIR}/resized_${TARGET_WIDTH}"

# Check if ImageMagick is installed
if ! command -v magick &> /dev/null && ! command -v convert &> /dev/null; then
    echo "Error: ImageMagick is not installed."
    echo "Install it using: sudo apt install imagemagick (Debian/Ubuntu) or brew install imagemagick (macOS)"
    exit 1
fi

# Use 'magick' for v7+ and 'convert' for v6
CMD="magick"
if ! command -v magick &> /dev/null; then
    CMD="convert"
fi

# Create output directory
mkdir -p "$OUT_DIR"

# Enable case-insensitive globbing for extensions (e.g., matches both .jpg and .JPG)
shopt -s nullglob nocaseglob
IMAGE_FILES=("$TARGET_DIR"/*.{jpg,jpeg,png,webp})

if [ ${#IMAGE_FILES[@]} -eq 0 ]; then
    echo "No JPG, PNG, or WEBP images found in $TARGET_DIR."
    exit 0
fi

echo "Resizing ${#IMAGE_FILES[@]} images to ${TARGET_WIDTH}px width..."
echo "Output folder: $OUT_DIR"
echo "------------------------------------------------------------"

# Loop through and resize
for img in "${IMAGE_FILES[@]}"; do
    filename=$(basename "$img")
    echo "Processing: $filename"
    
    # The "${TARGET_WIDTH}x" tells ImageMagick to set the width and auto-scale the height
    $CMD "$img" -resize "${TARGET_WIDTH}x" "$OUT_DIR/$filename"
done

echo "------------------------------------------------------------"
echo "✅ All done! Resized images are in $OUT_DIR"
