#!/bin/bash
# Objective:
# Delete the orphaned or forgotten Gnome versions (snap packages)
# if the `snap connections` command shows that `gnome-3-28-1804` or `gnome-3-38-2004` or any other gnome version are not connected to any applications in the left column,
# it means they have become orphaned, and in that case, you can manually uninstall them using `sudo snap remove gnome-3-28-1804` to free up space immediately.
# Note. This script was generated by  AI mode (Google).

echo "=== Searching for orphaned Gnome versions ==="
# 1. Get the list of all installed Gnome snaps
installed_gnome=$(snap list | awk '/^gnome-/ {print $1}')

# 2. Get the list of Gnome runtimes that have active connections
connected_gnome=$(snap connections | grep -E "gnome-[0-9]+" | awk '{print $3}' | cut -d: -f2 | sort -u)

orphans=()

# 3. Compare lists to identify orphans
for snap in $installed_gnome; do
    if ! echo "$connected_gnome" | grep -q "^$snap$"; then
        echo "❌ Orphan detected: $snap"
        orphans+=("$snap")
    fi
done

# 4. Handle confirmation and deletion
if [ ${#orphans[@]} -eq 0 ]; then
    echo "✅ System clean! You have no orphaned Gnome versions."
else
    echo ""
    read -p "Do you want to delete all (${#orphans[@]}) detected orphaned versions? (y/N): " confirm
    if [[ "$confirm" =~ ^[Yy]$ ]]; then
        for snap in "${orphans[@]}"; do
            echo "Removing $snap..."
            sudo snap remove "$snap"
        done
        echo "🎉 Cleanup completed successfully!"
    else
        echo "❌ Cleanup canceled. No packages were removed."
    fi
fi
